services:

  postgres:
    image: postgres:13.2
    env_file:
      .env
    ports:
      - '5432:5432'


  testing_system:
    build:
      context: .
      network: host
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env