# Generated by Django 4.1.2 on 2022-10-31 05:37

from django.db import migrations, models
import django.db.models.deletion
import main.models.test_suite


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test_alter_answer_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'набор тестов',
                'verbose_name_plural': 'наборы тестов',
                'db_table': 'test_suites',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='test_suite',
            field=models.ForeignKey(default=main.models.test_suite.provide_default_test_suite, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.testsuite', verbose_name='Набор тестов'),
        ),
    ]
